layout_spectrum: 0.9030354
color:
  saturation: 0.8364249
  lightness: 0.5193929
  brandStrength: 0.8288364
  brandColors:
    - '#050403'
    - '#FCFCF8'
    - '#413B2F'
    - '#AC9A88'
    - '#765316'
  rhythmicContrast: 0.608769
typography_spectrum: 0.346543
name: Bernie LaBarge
