layout_spectrum: 0.2409262
name: Bernie LaBarge
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6595744
  lightness: 0.5375469
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#050403'
    - '#FCFCF8'
    - '#413B2F'
    - '#AC9A88'
    - '#765316'
typography_spectrum: 0.9881101
